l_english:
 DECISION_ON_COOLDOWN:0 "@warning_icon!#X $DECISION_NAME$ unavailable until [DATE.GetStringLong]#!"
 ALREADY_PLANNING_ACTIVITY:0 "You are already planning another [activity|E]"
 train_decision:0 "Arrange a Training Session"
 train_decision_tooltip:1 "A Training Session will be held"
 train_decision_desc:0 "#F I hear the call of battle, and sense the need to exercise my body to prepare for it's arrival. Time to resolve some pent up rage!#!"
 train_decision_train:1 "You go on a #V Training Session#! in one of the baronies of your realm"
 train_decision_tt_header:0 "A successful training session will:"
 train_decision_prestige:1 "You may get opportunities to increase your [prestige|E]"
 train_decision_stress:0 "#P    Reduce your [stress|E]#!"
 train_decision_stress_lazy:0 "#N You will not lose [stress|E] since you are [GetTrait('lazy').GetName( GetPlayer )]#!"
 train_decision_stress_craven:0 "#N You will not lose [stress|E] since you are [GetTrait('craven').GetName( GetPlayer )]#!"
 train_decision_confirm:0 "Let's battle!"
 DECISION_COOLDOWN_WARNING:0 "@warning_icon!#X $DECISION_NAME$ will be unavailable for $COOLDOWN$#!"
 SHOW_DECISION_TOOLTIP:1 "#T [Decision.GetTitleForPlayer]#!\n[Decision.GetCommandDescForPlayer][Select_CString(StringIsEmpty(Decision.GetCommandDescForPlayer),'','\n')][Decision.GetShortDescForPlayer]"