l_english:
 held_train_modifier:0 "Trained Recently"
 held_train_modifier_desc:0 "This character has recently arranged a training session, and may not do so again until the specified date."
 
 train_peasants_denied_aid_modifier:0 "Peasants Denied Aid"
 train_peasants_denied_aid_desc_modifier:0 "You refused to aid peasants that asked for your help."
 
 train_peasants_hunted_modifier:0 "Peasants Hunted"
 train_peasants_hunted_desc_modifier:0 "You used peasants as your victims"
 
 train_aided_peasants_modifier:0 "Peasants Aided"
 train_aided_peasants_desc_modifier:0 "You helped impoverished peasants."
 
 train_peasants_given_aid_modifier:0 "Peasant Saved"
 train_peasants_given_aid_desc_modifier:0"You saved a peasant from certain death."
 
 train_peasants_denied_aid_modifier:0 "Peasant Left to Die"
 train_peasants_denied_aid_desc_modifier:0 "You allowed a peasant to be crushed to death."
 
 train_punished_locals_modifier:0 "You killed local bandits"
 train_punished_locals_modifier_desc:0 "You and your soilders killed local bandits."
 
 train_bandits_training_modifier:0 "You trained with local bandits"
 train_bandits_training_desc_modifier:0 "You trained with local bandits and got some good tips."
  
  train_local_garrison_modifier:0 "Allowed Locals to Join"
  train_local_garrison_desc_modifier:0 "You allowed the local garrison to join you training session."
  
  train_upset_garrison_modifier:0 "Didn't Allow Locals to Join"
  train_upset_garrison_desc_modifier:0 "You didn't allow the local garrison to join you training session."
  
  train_scorn_garrison_modifier:0 "Scolded Locals from Joining"
  train_scorn_garrison_desc_modifier:0 "You scolded the local garrison that tried to join your training session."
  
  train_protected_peasants_modifier:0 "Fooled peasants"
  train_protected_peasants_desc_modifier:0 "You conviced the locals that a peasant died in a training accident."
  
  train_tasted_the_belt_modifier:0 "Punished heir"
  train_tasted_the_belt_desc_modifier:0 "You called out your heir for killing a peasant."
  
  train_choose_truth_modifier:0 "You carried on"
  train_choose_truth_desc_modifier:0 "You didn't lie about injury to get out of training."
  
  train_mediated_fight_modifier:0 "You mediated a fight"
  train_mediated_fight_desc_modifier:0 "You calmed down the situation before it got out of hand."
  
  train_punished_nice_courtier_modifier:0 "You scolded them!"
  train_punished_nice_courtier_modifier_modifier:0 "You joined in and scolded then when they needed you."
  