l_english:
 train_header:0 "Train:"
 train.1001.t:1 "$train_header$ You prepare yourself"
 train.1001.desc:0 "My [ROOT.Char.Custom2('RelationToMeShort', SCOPE.sC('training_courtier_1') )], [training_courtier_1.GetTitledFirstName], and I stretch our muscles and prepare for a bout. \n\n[training_courtier_1.GetTitledFirstName] asks if we should use the training swords or our own blades? "
 train.1001.a:0 "Our own weapons, let's make this interesting!"
 train.1001.b:0 "Lets use the training swords."

 train.1002.desc_wounded_courtier:0 "We have a lively exchange, and suddenly one of my slashes catches [training_courtier_1.GetTitledFirstName] in the side of the face and [training_courtier_1.GetSheHe] falls to the ground, screaming.\n\nIt is nothing fatal, but [training_courtier_1.GetSheHe] is twisting in pain in the mud."
 train.1002.desc:0 "Just as [training_courtier_1.GetSheHe] attacks with a downward slash, I parry gracefully. Then I lunge, and [training_courtier_1.GetSheHe] deflects with finese.\n\n[training_courtier_1.GetTitledFirstName] and I continue these exchanges, neither gaining the upper hand. Suddenly one of my strikes knocks [training_courtier_1.GetTitledFirstName] to the ground, [training_courtier_1.GetTitledFirstName] wipes the dust off.\n\n"Shall we continue?""
 train.1002.a:0 "We need the practice, let's continue!"
 train.1002.b:0 "Let's take a quick rest then carry on."
 train.1002.c:0 "[training_courtier_1.GetFirstNameNoTooltip] must be given time to recover."

 train.1003.desc_beat:0 "I know i've won as I parry and riposte and [training_courtier_1.GetTitledFirstNamePossessive] eyes grow wide as [training_courtier_1.GetSheHe] barely manages to dodge.\n\nAs [training_courtier_1.GetHerHis] breathing grows heavier, I press my advantage. [training_courtier_1.GetTitledFirstName] flinches as I strike, spin, and strike again, disarming [training_courtier_1.GetHerHim] with my blade. Finally the dust clears with my blade at [training_courtier_1.GetHerHis] throat!"
 train.1003.desc_not_beat:0 "As I take my next swing [training_courtier_1.GetTitledFirstNamePossessive] ellegantly dodges under my blade, [training_courtier_1.GetSheHe] knocks me back with a mighty kick to the chest.\n\nAs I recover my senses I look up, and before I know what has happened [training_courtier_1.GetTitledFirstName] has [training_courtier_1.GetHerHis] blade to my neck. Seem's I lost this one."
 train.1003.desc_injured:0 "\n\nIt is regrettable that [training_courtier_1.GetTitledFirstName] had to be injured over a practice bout."
 train.1003.desc_uninjured:0 "\n\nWe relax our stances and brush ourselves off, [training_courtier_1.GetTitledFirstName] nods [training_courtier_1.GetHerHis] head at a battle well fought."
 train.1003.a:0 ""A good practice bout!" [training_courtier_1.GetSheHe] says."
 train.1003.a.tt:0 "Indeed it was!"
 train.1003.b:0 ""Next time you'll best me!" [training_courtier_1.GetSheHe] says."
 train.1003.b.tt:0 "Indeed I'll be ready for you!"

 train.1011.t:1 "$train_header$ Rude Vassal"
 train.1011.desc_horse:0 "Just as my [ROOT.Char.Custom2('RelationToMe', SCOPE.sC('nice_courtier') )] [nice_courtier.GetTitledFirstName] started to prepare for the training session,\n\n my [ROOT.Char.Custom2('DescriptorNegative', SCOPE.sC('hated_participant'))] [ROOT.Char.Custom2('RelationToMe', SCOPE.sC('hated_participant') )] [hated_participant.GetTitledFirstName] made a pre-emptive lunge, knocking [nice_courtier.GetHerHim] off balance and tumbling to the ground."
 train.1011.desc_talk:0 "After having a bout [hated_participant.GetTitledFirstName] knocks your [ROOT.Char.Custom2('RelationToMe', SCOPE.sC('nice_courtier') )] hard with force, down to the ground.\n\n"Look at that [nice_courtier.Custom('InsultAdjective')] [nice_courtier.Custom('InsultNoun')] [nice_courtier.GetFirstNameNoTooltip]!" [hated_participant.GetTitledFirstName] glares down at your [ROOT.Char.Custom2('RelationToMe', SCOPE.sC('nice_courtier') )].\n\nMy [ROOT.Char.Custom2('RelationToMe', SCOPE.sC('nice_courtier') )] [nice_courtier.GetTitledFirstName] seems to have a hard time bearing the insults."
 train.1011.a:1 "You fool, you embarrass us both."
 train.1011.b:0 "This is no way for a [hated_participant.GetTitleTierName] to act when training."
 train.1011.c:0 "Hah, [nice_courtier.GetFirstNameNoTooltip] has a lot to learn!"

 train.1012.desc:0 "Sword in hand and eyes on [hated_participant.GetTitledFirstName]... A slow deep breath as they approach quietly...\n\nMy [ROOT.Char.Custom2('DescriptorNegative', SCOPE.sC('hated_participant'))] [ROOT.Char.Custom2('RelationToMe', SCOPE.sC('hated_participant') )] is wearing an evil grin as they appraoch, they glance at me for confirmation."
 train.1012.a:0 "Then [hated_participant.GetTitleTierName] turned and frowned at me."
 train.1012.a.tt:0 "#EMP Swish!#!"
 train.1012.b:0 "Not here, not yet!"

 train.1013.desc:0 ""Such a shame that it was [hated_participant.GetHerHim] that had to die in a training accident.\n\n[hated_participant.GetSheHe] didn't deserve to die in such a manor..." The others are not questioning my story about [hated_participant.GetHerHis] tragic passing.\n\n"
 train.1013.a:0 "Such an unfortunate incident!"

 train.1014.desc:0 "As [hated_participant.GetTitledFirstName] falls backward to the earth, holding [hated_participant.GetHerHis] bleeding ear, the blade is dropped and I feign a look of horror.\n\n"You fool" [hated_participant.GetTitledFirstName] shouts as [hated_participant.GetTitledFirstName] gets back up off the ground."
 train.1014.a:1 "Well, no less than you deserved?"
 train.1014.all_honorable_train_participants:0 "All Honorable Participants of the training session:"
 train.1014.all_who_dislike_or_are_evil:0 "All Participants who dislike [hated_participant.GetFirstNameNoTooltip], or enjoy suffering:"
 train.1014.c:1 "You mean to blame clumsiness on for this?"

 train.1015.desc:0 "[hated_participant.GetTitledFirstName] stares wide-eyed at me, "What are you doing?!""
 train.1015.a:1 "Shrug un-apologetically."
 train.1015.b:1 "You had better forget about this!"
 train.1015.c:0 "Next time you won't be so lucky."
 train.1015.d:1 "This was an... unfortunate accident."
 train.1015.e:0 "I have ways of making [hated_participant.GetHerHim] forget about this."

 train.1016.desc:0 ""[ROOT.Char.GetTitledFirstNameNoTooltip], what are you doing?"\n\n[hated_participant.GetTitledFirstName] looks into your eyes, "Hah! Lost in vividly sadistics pranks again are we? My [ROOT.Char.GetLadyLord]?""
 train.1016.a:0 "Just you wait, [hated_participant.GetFirstNameNoTooltip]..."

 train.4001.t:1 "$train_header$ The beggers"
 train.4001.desc:0 "We have an active time of training, with several good bouts thus far, however I feel my patience wearing thin as beggers keep hassling the others for coin.\n\nSurely there must be better things to do in [activity_place.GetNameNoTier] than going around begging for coin, they should be working for it!"
 train.4001.a:0 "Guards, get these filtchers out of [activity_place.GetNameNoTier]!"
 train.4001.b:0 "We came here to train, did we not?"
 train.4001.special_interest:0 "Due to [county_owner.GetHerHis] unusual interests:"
 train.4001.c:0 "Oh, this could be a fine oppertunity..."
 train.4001.d:0 "A generous donation should keep them away long enough."
 
 train.4002.t:1 "$train_header$ The accident"
 train.4002.desc:0 "Half way through a bout with one of my soilders we hear it!"#EMP YYaagghh—!#!"\n\n A peasant is trapped under a large wagon and there looks to be only a little time before they are crushed! They thrash around on the floor as locals try and help, however they aren't strong enough to lift the wagon off on their own."
 train.4002.a:0 "Everyone follow me, let's get this off them... Heave!"
 train.4002.b:0 "We came here to train, leave the peasants to help their own!"
 train.4002.c:0 "Soilders, get to it then..."
 
 train.4003.t:1 "$train_header$ Thugs and holligans"
 train.4003.desc:0 "Further down the street we see a group hassling the locals for what looks like protection money.\n\nBandits, here in the [land_owner.GetTitleTierName]'s province? They notice us and start to spread out, trying to look less conspicuous.\n\nAs me and my fellows approach them, they look up. "We aren't up to no bad, your mercy." Their poorly concealed blades and knifes beg to differ."
 train.4003.a:0 "They will hang!"
 train.4003.b:0 ""You all seem to be well versed in combat, I have a thought...""
 
 train.4004.t:1 "$train_header$ The more the merrier"
 train.4004.desc:0 "As you continue praticing a group from the local garrison approach.\n\n"Welcome to [land_owner.GetTitleTierName]'s province. Mayhaps we join in?"\n\nThe garrison troops look eager to join your session."
 train.4004.a:0 ""Of course you can join.""
 train.4004.b:0 ""Shouldn't you men be at your posts?""
 train.4004.c:0 ""How dare you address me!""

 train.4008.t:1 "$train_header$ Errant Heir"
 train.4008.desc:0 "My [ROOT.Char.Custom2('RelationToMeShort', SCOPE.sC('heir_participant'))], [heir_participant.GetTitledFirstName] is engaged in a fierce bout. I follow [heir_participant.GetHerHis] every move. Suddenly an over zealous strike sends [heir_participant.GetHerHis] opponent to the ground lifeless.\n\nMy [ROOT.Char.Custom2('RelationToMeShort', SCOPE.sC('heir_participant'))], [heir_participant.GetTitledFirstName] looks shocked. "It was an accident I swear!"\n\nWe must do something before the rest of group begin to notice, and demand an explanation."
 train.4008.a:0 "[heir_participant.GetFirstNameNoTooltip] fought valiantly it was just a misplaced blow, I saw it!"
 train.4008.a.success:0 "Everyone believes me"
 train.4008.a.failure:0 "People do not buy the lie"
 train.4008.b:0 "We must cover this up."
 train.4008.b.success:0 "We manage to hide the body"
 train.4008.b.failure:0 "The body is found"
 train.4008.b.success_tt:0 "The body remains hidden"
 train.4008.c:0 "[heir_participant.GetFirstNameNoTooltip] must answer for [heir_participant.GetHerHis] crime."

 train.4009.t:1 "$train_header$ Feel the burn"
 train.4009.desc:0 "#EMP Swing—!#!\nAs I turn around. [schemer.GetTitledFirstName], my [ROOT.Char.Custom2('RelationToMeShort', SCOPE.sC('schemer'))], is standing behind me with his sword drawn and murderous resolve in [schemer.GetHerHis] eyes."
 train.4009.a:0 "You stand no chance against me!"
 train.4009.a.success:0 "I escape from [schemer.GetTitledFirstNameNoTooltip]"
 train.4009.a.failure:0 "I am wounded but escape from [schemer.GetTitledFirstNameNoTooltip]"
 train.4009.a.critical_failure:0 "[schemer.GetTitledFirstNameNoTooltip] defeats me"
 train.4009.b:0 "Help! Help! [saving_participant.GetFirstNameNoTooltip]!"
 train.4009.b.critical_success:0 "[saving_participant.GetTitledFirstNameNoTooltip] wounds [schemer.GetTitledFirstNameNoTooltip] and we escape"
 train.4009.b.failure:1 "[saving_participant.GetTitledFirstNameNoTooltip] is wounded but we escape from [schemer.GetTitledFirstNameNoTooltip]"
 train.4009.b.critial_failure:0 "[saving_participant.GetTitledFirstNameNoTooltip] fails to defend me"
 train.4009.c:0 "If I only can make it back to camp!"
 train.4009.c.failure:0 "[schemer.GetTitledFirstNameNoTooltip] catches me"

 train.4010.desc:0 "#EMP Swing—!#!\nAs we turn towards the source of the sound.\n\n[schemer.GetTitledFirstName], my [ROOT.Char.Custom2('RelationToMe', SCOPE.sC('schemer'))], is standing behind us with [schemer.GetHerHis] sword drawn, pointed towards [targeted_participant.GetFirstName]."
 train.4010.a:0 "Fear not, my [ROOT.Char.Custom2('RelationToMeShort', SCOPE.sC('targeted_participant'))]!"
 train.4010.a.critical_success:1 "I wound [schemer.GetFirstNameNoTooltip] and fend [schemer.GetHerHim] off"
 train.4010.a.failure:1 "[schemer.GetFirstNameNoTooltip] wounds me but we both get away"
 train.4010.a.critical_failure:0 "I fail to defend [targeted_participant.GetFirstNameNoTooltip]"
 train.4010.b:0 "Good luck, [targeted_participant.GetFirstNameNoTooltip]."
 train.4010.b.critical_success:1 "[targeted_participant.GetFirstNameNoTooltip] wounds [schemer.GetFirstNameNoTooltip] and fends [schemer.GetHerHim] off"
 train.4010.b.failure:1 "[targeted_participant.GetFirstNameNoTooltip] is wounded but escapes"
 train.4010.b.critical_failure:1 "[schemer.GetFirstNameNoTooltip] defeats [targeted_participant.GetFirstNameNoTooltip] and gets rid of any witnesses"
 train.4010.failure.murder_secret_tooltip:0 "I learn the Murder Secret"
 train.4010.c:0 "Help! [schemer.GetFirstNameNoTooltip] is assaulting my [ROOT.Char.Custom2('RelationToMeShort', SCOPE.sC('targeted_participant'))]!"
 train.4010.d:0 "#EMP Aggghhh—!#!"
 train.4010.d.tt:1 "This option is available because you are Honorable"

 train.4016.t:1 "$train_header$ The actor"
 train.4016.desc:0 "After a couple of bouts I begin to feel my muscles ache, I continue on for a couple more and feel my arms are shaking.\n\nIf I stop due to tired muscles the others will think less of me. I could just keep going, it would be unwise to let them see me as weak."
 train.4016.a:0 "I could convince them I need a break..."  
 train.4016.b:0 "I could feign injury..."   
 train.4016.b.success:0 "People believe my scheme"
 train.4016.b.failure:0 "My deceit is uncovered"
 train.4016.c:0 "I will not sink so low, I'd rather be bested than give up!"

 train.9001.t:1 "$train_header$ Returning from the training session"
 train.9001.desc_opening:0 "The training session is nearing completion. We all sheath our weapons and call it a day.\n\nThe servants clean up the armor and other weapons for the journey back, as the sun begins to set.\n\n"
 train.9001.desc_trainer_1:0 "I had my share of victories today, and people around me have started to take notice – word is spreading of my activities!\n\n"
 train.9001.desc_trainer_2:0 "The excitement of battle, and the thrill of victory is so entoxicating I wish I wouldn't end!\n\n"
 train.9001.desc_trainer_3:0 "No matter how fast, strong, or cunning the opponent, it stands no chance against me! My prowess as a warrior is the topic of many conversations across the realm. However, the true reward is the freedom that battle gives me."
 train.9001.desc_good_bad:0 "In spite of our difficulties during the day, the training session went very well!"
 train.9001.desc_good:0 "Bouts like these are a pure joy, I cannot wait for next time!"
 train.9001.desc_bad_good:0 "Everything that could go wrong seemed to do so, but there were silver linings to be found."
 train.9001.desc_bad:0 "Our session had no end of issues, and i'm glad it's done with."
 train.9001.desc_same:0 "To immerse oneself in battle, this is the true meaning of life!"
 train.9001.desc_fallback:0 "To heed the call of battle is usually thrilling, but I must admit that I found this session rather forgettable."
 train.9001.a:0 "We return home, tired but reinvigorated!"
 train.9001.b:0 "We return home exhausted."
 train.9001.c:0 "Let us leave this session behind for now."
 train.9001.d:0 "Let us return home."
